# frozen_string_literal: true

module Support::LiferTestHelpers::Shell
  # Silence output to STDOUT that is generated by test code. In some cases it's
  # not necessary for the developer to see messages meant for the end user.
  #
  # @yield Ruby code that should be evaluated while the STDOUT is being
  #   silenced.
  def with_stdout_silenced(&block)
    $stdout = StringIO.new

    return yield
  ensure
    $stdout = STDOUT
  end
end
