require "fileutils"
require "rss"

# Builds a simple, UTF-8, RSS 2.0[1] feed using the Ruby standard library's RSS
# features.
#
# The features of the generated feed attempt to follow the recommendations for
# RSS feeds specified by RSS Board[2].
#
# The RSS builder can be configured in a number of ways:
#
# 1. Boolean
#
#    Simply set `rss: true` or `rss: false` to enable or disable a feed for a
#    collection. If `true`, an RSS feed will be built to `name-of-collection.xml`
#
# 2. Simple
#
#    Simply set `rss: name-of-output-file.xml` to specify the name of the
#    output XML file.
#
# 3. Fine-grained
#
#    Provide an object under `rss:` for more fine-grained control over
#    configuration. The following sub-settings are supported:
#
#    - `count:` - The limit of RSS feed items that should be included in the
#      output document. Leave unset or set to `0` to include all entries.
#    - `managing_editor:` - the contents of the `<managingEditor>` node of the
#      RSS document. When unset, Lifer builds a valid `<managingEditor>` value
#      using the collection or root `author` value and a null email address to
#      ensure that RSS feed validators are satisfied.
#    - `url:` -  the path to the filename of the output XML file.
#
# [1]: https://www.rssboard.org/rss-specification
# [2]: https://www.rssboard.org/rss-profile
#
class Lifer::Builder::RSS < Lifer::Builder
  # Because Lifer has no reason to have record of anyone's email address, we
  # provide a non-email address so a <managingEditor> can be set and validated by
  # RSS validators.
  #
  # Note that `.invalid` is a special-use TLD[1] that helps us indicate that the
  # email address is definitely not real.
  #
  # [1]: https://datatracker.ietf.org/doc/html/rfc6761
  #
  DEFAULT_MANAGING_EDITOR_EMAIL = "editor@null.invalid"

  self.name = :rss
  self.settings = [
    rss: [
      :count,
      :managing_editor,
      :url
    ]
  ]

  class << self
    # Traverses and renders an RSS feed for each feedable collection in the
    # configured output directory for the Lifer project.
    #
    # @param root [String] The Lifer root.
    # @return [void]
    def execute(root:)
      Dir.chdir Lifer.output_directory do
        new(root: root).execute
      end
    end
  end

  # Traverses and renders an RSS feed for feedable collection.
  #
  # @return [void]
  def execute
    Lifer::Utilities.parallelized collections_with_feeds do |collection|
      next unless (filename = output_filename(collection))

      FileUtils.mkdir_p File.dirname(filename)

      File.open filename, "w" do |file|
        file.puts(
          rss_feed_for(collection) do |current_feed|
            max_index = max_feed_items(collection) - 1

            collection.entries
              .select { |entry| entry.feedable? }[0..max_index]
              .each { |entry| rss_entry current_feed, entry }
          end.to_feed
        )
      end
    end
  end

  private

  attr_reader :collections_with_feeds, :root

  def initialize(root:)
    @collections_with_feeds =
      Lifer.collections.select { |collection| collection.setting :rss }
    @root = root
  end

  # According to the RSS Board, the recommended format for the
  # `<managingEditor>` feed data is
  #
  #     editor@example.com (Editor Name)
  #
  # Unfortunately, Lifer has no reason to have record of the editor's email
  # address except for in RSS feeds, so if an `rss.managing_editor` is not
  # configured we'll do our best to at provide information managing editor's
  # that RSS feed validators are satisified with using other site configuration
  # containing an author's name. Example output:
  #
  #     editor@null.invalid (Configured Author Name)
  #
  # @param collection [Lifer::Collection]
  # @return [String] The managing editor string for a `<managingEditor>` RSS
  #   feed field.
  def managing_editor(collection)
    editor = collection.setting(:rss, :managing_editor)

    return editor if editor

    "%s (%s)" % [
      DEFAULT_MANAGING_EDITOR_EMAIL,
      Lifer.setting(:author, collection: collection)
    ]
  end

  # The amount of feed items to output to the RSS file. If set to 0, there is no
  # max limit of feed items.
  #
  # @param collection [Lifer::Collection]
  # @return [Integer]
  def max_feed_items(collection) = Lifer.setting(:rss, :count, collection:) || 0

  def output_filename(collection)
    strict = !collection.root?

    case collection.setting(:rss, strict:)
    when FalseClass, NilClass then nil
    when TrueClass
      File.join Dir.pwd, "#{collection.name}.xml"
    when Hash
      File.join Dir.pwd, collection.setting(:rss, :url, strict:)
    when String
      File.join Dir.pwd, collection.setting(:rss, strict:)
    end
  end

  # @fixme Using the W3C feed validation checker[1], I found that RSS feed items
  #   generated by Lifer are missing some recommended functionality. Reports
  #
  #   > This feed is valid, but interoperability with the widest range of feed
  #   > readers could be improved by implementing the following recommendations.
  #   >
  #   > An item should not include both pubDate and dc:date
  #   > (https://validator.w3.org/feed/docs/warning/DuplicateItemSemantics.html)
  #   >
  #   > item should contain a guid element
  #   > (https://validator.w3.org/feed/docs/warning/MissingGuid.html)
  #   >
  #   > content:encoded should not contain relative URL references
  #   > (https://validator.w3.org/feed/docs/warning/ContainsRelRef.html)
  #
  #   Regarding the `<content:encoded>` field... this seems to be more closely
  #   related to our Markdown parser implementation than the RSS feed generation
  #   itself.
  #
  #   [1]: https://validator.w3.org/feed/check.cgi
  #
  def rss_entry(rss_feed, lifer_entry)
    rss_feed.maker.items.new_item do |rss_feed_item|
      if (authors = lifer_entry.authors).any?
        rss_feed_item.author = authors.join(", ")
      end
      rss_feed_item.id = lifer_entry.permalink
      rss_feed_item.link = lifer_entry.permalink
      rss_feed_item.title = lifer_entry.title
      rss_feed_item.summary = lifer_entry.summary
      rss_feed_item.updated = Time.now.to_s
      rss_feed_item.content_encoded = lifer_entry.to_html
    end
  end

  # @fixme Using the W3C feed validation checker[1], I found that RSS feeds
  #   generated by Lifer are missing some recommended functionality. Reports:
  #
  #   > Missing atom:link with rel="self"
  #   > (https://validator.w3.org/feed/docs/warning/MissingAtomSelfLink.html)
  #
  #   [1]: https://validator.w3.org/feed/check.cgi
  #
  def rss_feed_for(collection, &block)
    feed_object = nil

    ::RSS::Maker.make "rss2.0" do |feed|
      feed.channel.description =
        Lifer.setting(:description, collection: collection) ||
          Lifer.setting(:site_title, collection: collection)

      feed.channel.language = Lifer.setting(:language, collection: collection)

      feed.channel.lastBuildDate = Time.now.to_s

      feed.channel.link = "%s/%s" % [
        Lifer.setting(:global, :host),
        Lifer.setting(:rss, collection: collection)
      ]

      feed.channel.managingEditor = managing_editor(collection)
      feed.channel.title = Lifer.setting(:title, collection: collection)
      feed.channel.webMaster =
        Lifer.setting(:site_default_author, collection: collection)

      yield feed

      feed_object = feed
    end
    feed_object
  end
end
